const canvas=document.getElementById('pageCanvas'),ctx=canvas.getContext('2d'),area=document.getElementById('canvasArea');
const W=900,H=1200;let zoom=1,tool='pen',color='#202020',size=4,drawing=false,last=null,history=[],redoStack=[],current=0;
let db={name:'My JEE Notes',pages:[newPage()],bookmarks:[],tags:[],theme:'dark',notebooks:['My JEE Notes']};
function newPage(){return{strokes:[],texts:[],images:[],bookmark:false,tag:''}}
function save(){localStorage.setItem('noteflowPro',JSON.stringify(db));document.getElementById('saveState').textContent='● Saved'}
function load(){try{let x=JSON.parse(localStorage.getItem('noteflowPro'));if(x)db=x}catch(e){}}
function snapshot(){history.push(JSON.stringify(db.pages[current]));if(history.length>50)history.shift();redoStack=[]}
function paper(){let p=document.getElementById('paper').value;ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#d8dce2';ctx.fillStyle='#aaa';if(p==='ruled'||p==='four')for(let y=70;y<H;y+=38){ctx.beginPath();ctx.moveTo(30,y);ctx.lineTo(W-30,y);ctx.stroke()}if(p==='four')for(let y=70;y<H;y+=38){ctx.beginPath();ctx.moveTo(30,y-5);ctx.lineTo(W-30,y-5);ctx.stroke();ctx.beginPath();ctx.moveTo(30,y+5);ctx.lineTo(W-30,y+5);ctx.stroke()}if(p==='dots')for(let y=35;y<H;y+=28)for(let x=35;x<W;x+=28){ctx.beginPath();ctx.arc(x,y,1.2,0,7);ctx.fill()}if(p==='squares'){for(let x=0;x<W;x+=28){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=28){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}}
function render(){paper();let p=db.pages[current];p.strokes.forEach(draw);p.texts.forEach(t=>{ctx.fillStyle=t.color;ctx.font=`${t.size}px system-ui`;ctx.fillText(t.text,t.x,t.y)});p.images.forEach(im=>{let img=new Image();img.onload=()=>ctx.drawImage(img,im.x,im.y,im.w,im.h);img.src=im.src});document.getElementById('pageLabel').textContent=`${current+1} / ${db.pages.length}`;document.getElementById('pageCount').textContent=db.pages.length;updateThumbs()}
function draw(s){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=s.size;ctx.strokeStyle=s.color;if(s.type==='highlighter'){ctx.globalAlpha=.25;ctx.lineWidth=s.size*2.5}if(s.type==='pencil'){ctx.globalAlpha=.75}ctx.beginPath();if(['pen','pencil','highlighter','eraser'].includes(s.type)){s.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}else{let a=s.points[0],b=s.points[1];ctx.moveTo(a.x,a.y);if(s.type==='line')ctx.lineTo(b.x,b.y);if(s.type==='arrow'){ctx.lineTo(b.x,b.y);let ang=Math.atan2(b.y-a.y,b.x-a.x),h=14;ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-h*Math.cos(ang-.5),b.y-h*Math.sin(ang-.5));ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-h*Math.cos(ang+.5),b.y-h*Math.sin(ang+.5))}if(s.type==='rect')ctx.rect(a.x,a.y,b.x-a.x,b.y-a.y);if(s.type==='circle'){let r=Math.hypot(b.x-a.x,b.y-a.y);ctx.arc(a.x,a.y,r,0,Math.PI*2)}ctx.stroke()}ctx.restore()}
function pos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
function eraseAt(q){let r=Math.max(8,size*1.35);db.pages[current].strokes=db.pages[current].strokes.filter(s=>{if(s.type==='eraser')return true;return !s.points.some(p=>Math.hypot(q.x-p.x,q.y-p.y)<=r)})}
canvas.addEventListener('pointerdown',e=>{if(tool==='text'){let q=pos(e);openText(q);return}snapshot();drawing=true;last=pos(e);if(tool==='eraser'){eraseAt(last);render()}});
canvas.addEventListener('pointermove',e=>{if(!drawing)return;let q=pos(e);if(tool==='eraser'){eraseAt(q);render();last=q;return}let s={type:tool,size:+document.getElementById('size').value,color:document.getElementById('color').value,points:[last,q]};db.pages[current].strokes.push(s);draw(s);last=q});
['pointerup','pointercancel','pointerleave'].forEach(x=>canvas.addEventListener(x,()=>{if(drawing){drawing=false;save()}}));
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool});
document.getElementById('size').oninput=e=>{size=+e.target.value;document.getElementById('sizeVal').textContent=size+' px'};
document.getElementById('color').oninput=e=>color=e.target.value;
document.getElementById('paper').onchange=render;
document.getElementById('zoomIn').onclick=()=>setZoom(zoom+.1);document.getElementById('zoomOut').onclick=()=>setZoom(zoom-.1);document.getElementById('zoomFit').onclick=()=>setZoom(1);
function setZoom(z){zoom=Math.min(5,Math.max(.25,z));canvas.style.transform=`scale(${zoom})`;canvas.style.marginBottom=`${H*(zoom-1)}px`;document.getElementById('zoomVal').textContent=Math.round(zoom*100)+'%'}
function addPage(){db.pages.splice(current+1,0,newPage());current++;save();render()}
document.getElementById('newPage').onclick=addPage;
document.getElementById('prev').onclick=()=>{if(current){current--;render()}};document.getElementById('next').onclick=()=>{if(current<db.pages.length-1){current++;render()}};
document.getElementById('clear').onclick=()=>{snapshot();db.pages[current]=newPage();save();render()};
document.getElementById('duplicate').onclick=()=>{db.pages.splice(current+1,0,JSON.parse(JSON.stringify(db.pages[current])));current++;save();render()};
document.getElementById('bookmark').onclick=()=>{db.pages[current].bookmark=!db.pages[current].bookmark;save();render()};
document.getElementById('undo').onclick=()=>{if(!history.length)return;redoStack.push(JSON.stringify(db.pages[current]));db.pages[current]=JSON.parse(history.pop());save();render()};
document.getElementById('redo').onclick=()=>{if(!redoStack.length)return;history.push(JSON.stringify(db.pages[current]));db.pages[current]=JSON.parse(redoStack.pop());save();render()};
document.getElementById('noteTitle').oninput=e=>{db.name=e.target.value;save()};
document.getElementById('newNotebook').onclick=()=>{let n=prompt('Notebook name');if(n){db.notebooks.push(n);db.name=n;document.getElementById('noteTitle').value=n;save();renderNotebooks()}};
function renderNotebooks(){let el=document.getElementById('notebooks');el.innerHTML='';db.notebooks.forEach((n,i)=>{let d=document.createElement('div');d.className='notebook '+(n===db.name?'active':'');d.textContent='📓 '+n;d.onclick=()=>{db.name=n;document.getElementById('noteTitle').value=n;save();renderNotebooks()};el.appendChild(d)})}
function updateThumbs(){let el=document.getElementById('thumbs');el.innerHTML='';db.pages.forEach((p,i)=>{let d=document.createElement('div');d.className='thumb '+(i===current?'active':'');let c=document.createElement('canvas');c.width=180;c.height=240;let x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,180,240);x.strokeStyle='#ddd';for(let y=14;y<240;y+=8){x.beginPath();x.moveTo(5,y);x.lineTo(175,y);x.stroke()}let sx=W/180,sy=H/240;p.strokes.forEach(s=>{x.save();x.scale(1/sx,1/sy);drawOn(x,s);x.restore()});d.appendChild(c);let n=document.createElement('span');n.className='num';n.textContent=(i+1)+(p.bookmark?' ★':'');d.appendChild(n);d.onclick=()=>{current=i;render()};el.appendChild(d)})}
function drawOn(x,s){x.lineCap='round';x.lineJoin='round';x.lineWidth=s.size;x.strokeStyle=s.color;if(s.type==='highlighter')x.globalAlpha=.25;x.beginPath();s.points.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.stroke()}
function openText(q){let body=`<h2>Add text</h2><textarea id="txt" rows="5" placeholder="Write text..."></textarea><button id="addTxt">Add</button>`;modal(body);document.getElementById('addTxt').onclick=()=>{let v=document.getElementById('txt').value.trim();if(v){snapshot();db.pages[current].texts.push({text:v,x:q.x,y:q.y,color:document.getElementById('color').value,size:Math.max(14,size*5)});save();render()}closeModal()}}
const modalEl=document.getElementById('modal'),modalBody=document.getElementById('modalBody');function modal(x){modalBody.innerHTML=x;modalEl.classList.remove('hidden')}function closeModal(){modalEl.classList.add('hidden')}document.getElementById('closeModal').onclick=closeModal;
document.getElementById('searchBtn').onclick=()=>{let q=prompt('Search text in your notes');if(!q)return;let hits=[];db.pages.forEach((p,i)=>p.texts.forEach(t=>{if(t.text.toLowerCase().includes(q.toLowerCase()))hits.push(`Page ${i+1}: ${t.text}`)}));modal('<h2>Search results</h2>'+(hits.length?hits.map(h=>`<div class="result">${h}</div>`).join(''):'<p>No typed-text matches found.</p>'))};
document.getElementById('tagsBtn').onclick=()=>modal('<h2>Bookmarks & Tags</h2>'+db.pages.map((p,i)=>`<div class="result">Page ${i+1} ${p.bookmark?'⭐ Bookmarked':''} ${p.tag?'<b>#'+p.tag+'</b>':''}</div>`).join(''));
document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('light');db.theme=document.body.classList.contains('light')?'light':'dark';save()};
document.getElementById('backupBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db)],{type:'application/json'}));a.download=(db.name||'notebook')+'.noteflow';a.click()};
document.getElementById('restoreBtn').onclick=()=>document.getElementById('restoreInput').click();
document.getElementById('restoreInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);current=0;save();document.getElementById('noteTitle').value=db.name||'Notebook';renderNotebooks();render()}catch{alert('Invalid notebook file')}};r.readAsText(f)};
document.getElementById('imageBtn').onclick=()=>document.getElementById('imageInput').click();
document.getElementById('imageInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{snapshot();db.pages[current].images.push({src:r.result,x:80,y:100,w:300,h:220});save();render()};r.readAsDataURL(f)};
document.getElementById('aiBtn').onclick=()=>modal('<h2>✨ Study Assistant</h2><p>This offline build includes the assistant panel UI. Connect your preferred AI API to enable summaries, explanations, flashcards and question generation without changing the notebook engine.</p><textarea placeholder="Paste a concept or question here..."></textarea>');
document.getElementById('moreBtn').onclick=()=>document.getElementById('drawer').classList.toggle('hidden');document.getElementById('fab').onclick=()=>document.getElementById('drawer').classList.toggle('hidden');
document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('hidden');
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();document.getElementById('undo').click()}if((e.ctrlKey||e.metaKey)&&e.key==='y'){e.preventDefault();document.getElementById('redo').click()}if(e.key==='+'&&e.ctrlKey){e.preventDefault();setZoom(zoom+.1)}if(e.key==='-'&&e.ctrlKey){e.preventDefault();setZoom(zoom-.1)}});
async function exportPDF(){if(!window.jspdf){alert('PDF engine is loading; try again.');return}let old=current;const {jsPDF}=window.jspdf;let pdf=new jsPDF({unit:'px',format:[W,H]});for(let i=0;i<db.pages.length;i++){current=i;render();let img=canvas.toDataURL('image/jpeg',.92);if(i)pdf.addPage([W,H]);pdf.addImage(img,'JPEG',0,0,W,H)}current=old;render();pdf.save((db.name||'notes')+'.pdf')}
document.getElementById('exportPdf').onclick=exportPDF;
load();document.getElementById('noteTitle').value=db.name;document.body.classList.toggle('light',db.theme==='light');renderNotebooks();render();setZoom(1);
